name: Update Version

on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: Exafunction
          repo: codeium
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
